pipeline {
    // 1. Where to execute the pipeline
    agent {
        docker {
            image 'zephyr-build-env:latest' // The Docker image you want to use
            args '-u root'         // Optional: Run container as root user if needed
        }
    }
    // 3. The execution steps divided into stages
    stages {
        stage('Checkout') {
            steps {
                // Jenkins automatically checks out the code before the pipeline starts
                checkout scm
            }
        }

        // 2. Poll GitHub every 2 minutes for new commits
        triggers {
            pollSCM('H/2 * * * *')
        }

        stage('Static Analysis') {
            steps {
                echo "Running Cppcheck (We will add this in Stage 3)"
            }
        }
        stage('TEST SIMULATION - QEMU') {
            steps {
                sh'''
                # 1. Build specifically for virtual QEMU target
                west build -p always -b qemu_cortex_m3 firmware/ -d build_qemu

                # 2. Run your Python smoke test
                python3 simulation/qemu/run_qemu_test.py
                '''
            }
        }

        stage('Build Firmware') {
            steps {
                sh '''
                    # Build physical release artifact only after simulation passes
                    west build -p always -b nucleo_f401re firmware/
                '''
            }
        }

        stage('Test') {
            steps {
                echo 'Running automated tests...'
                
            }
        }
        stage('Deploy') {
            // Conditional execution
            when {
                branch 'main'
            }
            steps {
                echo 'Deploying to production...'
            }
        }
    }

    // 4. Actions to run depending on build outcomes
    post {
        always {
            echo 'Cleaning up the workspace...'
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Sending alerts...'
        }
    }
}